//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovayaColledge.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int ZakazId { get; set; }
        public System.DateTime ZakazDate { get; set; }
        public int EmployeeId { get; set; }
        public int UserId { get; set; }
        public int ItemId { get; set; }
        public string Description { get; set; }
    }
}
